### ISSUE TITLE
【検討】デザイン

### ISSUE THREAD

**Issue by minusvoid** [kougakusai/kougakusai-hp#44]
1. 開催日表示（右上）を画像・CSSどちらで実装するか（CSSの場合：デザイン）
2. トップページ背景画像の文字更新（保守性：模様と文字分割）
3. [SNSアイコンサイズ統一](https://github.com/kougakusai/kougakusai-hp/issues/19)
4. 小見出し下`margin`が`indexページ（30px）`と`他（5px）`で異なる
5. 記事本文`pタグ`の`padding`が`indexページ（0）`と`他（6px）`で異なる
6. 記事領域の`padding`が`indexページ（5%）`と`他（3%）`で異なる
7. `404ページ`デザイン
8. `aタグ`文字色
9. トップページ背景画像横幅とレスポンシブ閾値の値が一致していない
10. 協賛企業一覧ページがページ見出しと小見出しで内容が重複している
11. モバイル表示時`MENU`がフォーカス外れても開いたままなのはUX的に適切か
12. 画像掲載団体の掲載ページデザイン

*具体的な数値例は`Desktop版`

**Comment by kazuhiro-f** [comment]
1、2、3、7、12は対応済み。
残りのものについては個別にIssueを立て直します（話題が複数あると分かりづらいので）。
